CREATE PROCEDURE SP_INSERT_MARCA
	@Marca varchar(100)
	AS
BEGIN
insert into Marca Values(@Marca)
END

EXEC SP_INSERT_MARCA 'Volkswagen'
EXEC SP_INSERT_MARCA 'Jeep'
EXEC SP_INSERT_MARCA 'Chevrolet'
EXEC SP_INSERT_MARCA 'Toyota'
EXEC SP_INSERT_MARCA 'Honda'

SELECT * FROM MARCA